### ISSUE TITLE
人物描述的缩写算法

### ISSUE THREAD

**Issue by lidingpku** [cnschema/cdata#2]
目标： 
* 把百科人物描述的大段文字缩写为30～50个字的短句子，保持句子的完整性。
* 形成一个量化评估summary效果的方案。例如random 50, human evaluation
* 中文英文summary 方法不全一样

思路
* 明确问题，算法的输入，输出
* 明确评价算法结果的方法
* 找相关实现方法github, stackoverflow, 论文，对比reported benchmark
* 自己实现
* 单元测试，保证算法可用性
* 评价结果，评价算法正确率
* pull-request 提交代码，code review 

例如：
石孝友，南宋词人，字次仲，江西南昌人。生卒年不详。宋孝宗乾道二年（1166）进士。填词常用俚俗之语，状写男女情爱。仕途不顺，不羡富贵，隐居于丘壑之间。 石孝友著有《金谷遗音》，《直斋书录解题》著录一卷，明《唐宋名贤百家词》本作《金谷词》，不分卷。有明汲古阁《宋六十名家词》本、《四部备要》排印本。《全宋词》据毛□校汲古阁本收录。 \n石孝友，南宋词人，字次仲，江西南昌人。生卒年不详。宋孝宗乾道二年（1166）进士。填词常用俚俗之语，状写男女情爱。仕途不顺，不羡富贵，隐居于丘壑之间。 石孝友著有《金谷遗音》，《直斋书录解题》著录一卷，明《唐宋名贤百家词》本作《金谷词》，不分卷。有明汲古阁《宋六十名家词》本、《四部备要》排印本。《全宋词》据毛□校汲古阁本收录。\n

==》

石孝友，南宋词人，字次仲，江西南昌人。

数据：
[person1707.json.zip](https://github.com/cnschema/cdata/files/1141161/person1707.json.zip)

参考：
* https://en.wikipedia.org/wiki/Automatic_summarization
* http://dl.acm.org/citation.cfm?id=2188995
* https://github.com/search?utf8=%E2%9C%93&q=text+summary&type=
* https://github.com/search?utf8=%E2%9C%93&q=text+summarization&type=

**Comment by kn2322** [comment]
以下是对算法底线的初步调研。调研在交代算法满意度底线的同时完善了对算法的评估方法及评估标准。底线的满意度是 0.36。下一步是作出满意度和可用性上的改善，提升 0.36 这个结果。

首先，就算法满意度而言。3人对于50个缩写进行了判断，给了1或0的结果。1代表达到期望缩写标准，0代表未达到。对所有判断作出统计后，最基本摘取第一句的缩写算法达到 .36 的平均。这个数值是相当准确的，因为把数据数量减到25的数值是相近的 0.4。

其次，就评估方法而言。3个人首先各做了20个判断。然后，我们讨论了不同判断的原因，直到三人意见达到一致。最后的30个判断便有了更高的准确率。选择三人的原因是因为在后阶段平均这3人的3个判断不会出现平手。

最后，就评估标准而言：

标准：
1. 看缩写是否能概括原文中写到的主要知识 （—家，作品，使其出名的事情）
2. 看字数是否在30-50字之间
3. 如果聊天机器人给你缩写为回复，你是否会满意？
4. 作出综合评价
_身份重要、性格，生活时代，句式，主要贡献，作品，获奖，别名外号无用，特例应对，字数和完整度_

1-4为最初的标准，Italics的为讨论后对标准的改进。这个评估标准的重点在于对普通人的可用性和相关性。所以在长度，人性化度，和内容上都有特定的要求。比如说，一个人的诸多别名外号并没有他或她的主要文学作品重要。因此，一个更成功的算法必须要对应这些受众要求来做出判断。长度也是问题之一，这个算法的长度很不平均，有大概率在30-50字以外，是个需考虑的问题。此外，有少数描述不完整，或有重复的句子，或根本不是人物描述。

总而言之，这次评估给新算法做出了效果和可用性的底线；给评估的方法做出了案例；也完善了成功缩写算法的标准。下一步是研究在此提到的诸多问题（可用性，受众要求），以及对相关算法（TextRank等）作出测试及研究。

**Comment by kn2322** [comment]
[person.json.zip](https://github.com/cnschema/cdata/files/1158929/person.json.zip)
The json file containing Person data from 百度百科. Place it in local/person to use it in 'task_summarize_all_person' in summary.py, which generates a 'shortDescription' column in a new file, which is in cdata/cdata.

**Comment by kn2322** [comment]
人物描述缩写的 summarize_entity_person 函数最终以模板的形式实现。模板包含了用户最会想知道的属性：
1. 名称，生活时期，国籍或家乡，身份
2. 作品，有名称号（例：诗仙）（称号能做出知名度排名，再跟人物总体知名度比较来做出放进判断），成就
3. 特点
4. 此外基本无用

这些属性是人工判断之后决定的。模板中，人物属性有就用，没有就不用。模板为以下：
"{name}，字{courtesyName}，别名{alternateName}，号{artName}，{dynasty}人，祖籍{ancestralHome}，{birthDate}出生于{birthPlace}，{nationality}{occupation}，主要作品有{authorOf}，主要成就：{accomplishment}。"

成果满意，三个人主观人工评价100个热门人物（人工判断）的结果为 0.88。虽然字数没有控制，模板也有生硬之处，但总体结果是满意的。
